name: CI-Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  ECR_URI_AUTH: ${{ secrets.ECR_URI_AUTH }}
  ECR_URI_WEATHER: ${{ secrets.ECR_URI_WEATHER }}
  ECR_URI_UI: ${{ secrets.ECR_URI_UI }}
  SONAR_HOST_URL: https://sonarcloud.io

jobs:

  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Scan for UI
        run: snyk test
        working-directory: ./UI
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Scan for auth
        run: snyk test
        working-directory: ./auth
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Scan for weather
        run: snyk test
        working-directory: ./weather
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  sonarQubeScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          host-url: 'http://13.221.216.62:9000'
          login: ${{ secrets.SONAR_TOKEN }}
  build-and-analyze:
    name: Build, Push & Analyze Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./UI
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set short commit SHA
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push Auth Image
        run: |
          docker build -t $ECR_URI_AUTH:${TAG} ./auth
          docker push $ECR_URI_AUTH:${TAG}

      - name: Build & Push Weather Image
        run: |
          docker build -t $ECR_URI_WEATHER:${TAG} ./weather
          docker push $ECR_URI_WEATHER:${TAG}

      - name: Build & Push UI Image
        run: |
          docker build -t $ECR_URI_UI:${TAG} ./UI
          docker push $ECR_URI_UI:${TAG}

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=IT-Visionary-Devsecops-Project
            -Dsonar.organization=visionary-team2025
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
